package uhc.command.commands;

import uhc.arguments.entity.Entity;
import uhc.command.MinecraftCommand;
import uhc.score.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * 📊 **Scoreboard Command Builder**
 * <p>
 * A specialized abstract builder for constructing Minecraft {@code /scoreboard} commands.
 * This class uses method-based branching to separate <b>Objectives</b> and <b>Players</b> logic,
 * ensuring type safety and valid syntax at compile time.
 * </p>
 */
public abstract class ScoreboardCommand implements MinecraftCommand {

    // --- 🏗️ Entry Points ---

    /**
     * Initiates a command sequence targeting scoreboard objective definitions.
     * @return A specialized {@link ObjectiveBuilder} for objective management.
     */
    public static ObjectiveBuilder objectives() {
        return new ObjectiveBuilder();
    }

    /**
     * Initiates a command sequence targeting player score values.
     * @return A specialized {@link PlayerBuilder} for score manipulation.
     */
    public static PlayerBuilder players() {
        return new PlayerBuilder();
    }

    /**
     * Begins a batch operation to generate multiple commands at once.
     * @return A builder for handling multiple scoreboard actions.
     */
    public static BatchBuilder batch() {
        return new BatchBuilder();
    }

    // --- ⚙️ Core Contract ---

    /**
     * Returns the final command string generated by the specific builder branch.
     * @return The raw Minecraft command.
     */
    @Override
    public abstract String generate();

    /**
     * Standard override to allow the builder to be used directly in string concatenation.
     * @return The result of {@link #generate()}.
     */
    @Override
    public String toString() {
        try {
            return generate();
        } catch (Exception e) {
            return "/* Error generating command: " + e.getMessage() + " */";
        }
    }

    // --- 📦 Batch Management Branch ---

    /**
     * Handles bulk generation of scoreboard commands, primarily for registry initialization.
     */
    public static class BatchBuilder {

        /**
         * Generates a list of ScoreboardCommand objects (builders) for all registered objectives.
         * <p><b>Error Catching:</b> Skips null entries in the registry and ensures
         * display logic only triggers for flagged objectives.</p>
         * @return A list of initialized ScoreboardCommand builders.
         */
        public List<ScoreboardCommand> registerAll() {
            List<ScoreboardCommand> commandList = new ArrayList<>();

            try {
                for (uhc.score.ScoreboardObjective obj : uhc.score.ScoreboardObjectives.ALL) {
                    if (obj == null) continue;

                    // 1. Add the "Add Objective" builder
                    commandList.add(ScoreboardCommand.objectives().add(obj));

                    // 2. Add the "Set Display" builder if flagged for sidebar
                    if (obj.isDisplaySidebar()) {
                        commandList.add(ScoreboardCommand.objectives()
                                .setDisplay(uhc.score.DisplaySlot.SIDEBAR, obj.getId()));
                    }
                }
            } catch (Exception e) {
                // Log or wrap the error to prevent total initialization failure
                throw new RuntimeException("Failed to compile objective registration batch.", e);
            }
            return commandList;
        }
    }

    // --- 🎯 Objective Management Branch ---

    /**
     * 🎯 **Objective Builder**
     * <p>Handles sub-commands under {@code /scoreboard objectives}, such as
     * adding, removing, or setting display slots for objectives.</p>
     */
    public static class ObjectiveBuilder extends ScoreboardCommand {

        /** The partial command string containing sub-action logic. */
        private String command;

        /**
         * Configures the command to register a new scoreboard objective.
         * <p><b>Syntax:</b> {@code objectives add <name> <criteria> [displayName]}</p>
         * @param obj The {@link ScoreboardObjective} data model.
         * @return This builder instance for method chaining.
         * @throws NullPointerException if the provided objective object is null.
         * @throws IllegalStateException if the objective name exceeds Minecraft's 16-char limit.
         */
        public ObjectiveBuilder add(ScoreboardObjective obj) {
            Objects.requireNonNull(obj, "Objective data model cannot be null.");

            // Perform internal validation on the ID before attempting to build
            try {
                obj.getId().validate();
            } catch (Exception e) {
                throw new IllegalStateException("Invalid Objective ID: " + e.getMessage());
            }

            StringBuilder sb = new StringBuilder("add ")
                    .append(obj.getId().getObjectiveName())
                    .append(" ")
                    .append(obj.getCriteria().getCriteriaName());

            // Handle the optional JSON display name component
            if (obj.getDisplayName() != null) {
                sb.append(" ").append(obj.getDisplayName().build());
            }

            this.command = sb.toString();
            return this;
        }

        /**
         * Configures the command to delete an existing objective.
         * @param id The unique {@link ScoreboardObjectiveId} to remove.
         * @return This builder instance for method chaining.
         * @throws NullPointerException if the ID is null.
         */
        public ObjectiveBuilder remove(ScoreboardObjectiveId id) {
            Objects.requireNonNull(id, "Objective ID to remove cannot be null.");
            this.command = "remove " + id.getObjectiveName();
            return this;
        }

        /**
         * Configures where an objective should be displayed on the screen.
         * @param slot The {@link DisplaySlot} (e.g., sidebar).
         * @param id The objective to show, or null to clear the slot.
         * @return This builder instance for method chaining.
         * @throws NullPointerException if the slot is null.
         */
        public ObjectiveBuilder setDisplay(DisplaySlot slot, ScoreboardObjectiveId id) {
            Objects.requireNonNull(slot, "Display slot cannot be null.");
            this.command = "setdisplay " + slot.getSlotName() + (id != null ? " " + id.getObjectiveName() : "");
            return this;
        }

        /**
         * Finalizes the {@code /scoreboard objectives} command.
         * @return The formatted command string.
         * @throws IllegalStateException if no action was defined.
         */
        @Override
        public String generate() {
            if (command == null) {
                throw new IllegalStateException("ObjectiveBuilder requires an action (add, remove, setdisplay).");
            }
            return "scoreboard objectives " + command;
        }
    }

    // --- ⚔️ Player Management Branch ---

    /**
     * ⚔️ **Player Builder**
     * <p>Handles sub-commands under {@code /scoreboard players}, focusing on
     * modifying and querying scores for specific entities.</p>
     */
    public static class PlayerBuilder extends ScoreboardCommand {

        /** The entity or selector targeted by this command. */
        private Entity target;

        /** The partial command string containing the operation and value logic. */
        private String subCommand;

        /**
         * Defines the entity whose scores will be modified.
         * @param target The {@link Entity} selector.
         * @return This builder instance for method chaining.
         * @throws NullPointerException if the target is null.
         */
        public PlayerBuilder target(Entity target) {
            this.target = Objects.requireNonNull(target, "Player target entity cannot be null.");
            return this;
        }

        /**
         * Sets a player's score to a specific value.
         * @param id The objective to modify.
         * @param score The numerical value to set.
         * @return This builder instance.
         */
        public PlayerBuilder set(ScoreboardObjectiveId id, int score) {
            Objects.requireNonNull(id, "Objective ID for 'set' action cannot be null.");
            this.subCommand = "set " + id.getObjectiveName() + " " + score;
            return this;
        }

        /**
         * Increments a player's score by a specific amount.
         * @param id The objective to modify.
         * @param score The amount to add.
         * @return This builder instance.
         */
        public PlayerBuilder add(ScoreboardObjectiveId id, int score) {
            Objects.requireNonNull(id, "Objective ID for 'add' action cannot be null.");
            this.subCommand = "add " + id.getObjectiveName() + " " + score;
            return this;
        }

        /**
         * Completely removes a player's score from an objective.
         * @param id The objective to reset, or null to reset all scores for the player.
         * @return This builder instance.
         */
        public PlayerBuilder reset(ScoreboardObjectiveId id) {
            this.subCommand = "reset" + (id != null ? " " + id.getObjectiveName() : "");
            return this;
        }

        /**
         * Finalizes the {@code /scoreboard players} command.
         * @return The formatted command string.
         * @throws IllegalStateException if the target or sub-action is missing.
         */
        @Override
        public String generate() {
            if (target == null) {
                throw new IllegalStateException("PlayerBuilder requires a target entity (use .target()).");
            }
            if (subCommand == null) {
                throw new IllegalStateException("PlayerBuilder requires an action (set, add, reset).");
            }

            // Injects the target between the action and the objective/value
            try {
                return "scoreboard players " + subCommand.replaceFirst(" ", " " + target + " ");
            } catch (Exception e) {
                throw new IllegalStateException("Unexpected error assembling player command: " + e.getMessage());
            }
        }
    }
}