package uhc.command.commands;

import uhc.arguments.entity.Entity;
import uhc.command.MinecraftCommand;
import uhc.score.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * 📊 **Scoreboard Command Builder**
 * <p>
 * A specialized abstract builder for constructing Minecraft {@code /scoreboard} commands.
 * This class uses method-based branching to separate <b>Objectives</b> and <b>Players</b> logic,
 * ensuring type safety and valid syntax at compile time.
 * </p>
 */
public abstract class ScoreboardCommand implements MinecraftCommand {

    // --- 🏗️ Entry Points ---

    /**
     * Initiates a command sequence targeting scoreboard objective definitions.
     * @return A specialized {@link ObjectiveBuilder} for objective management.
     */
    public static ObjectiveBuilder objectives() {
        return new ObjectiveBuilder();
    }

    /**
     * Initiates a command sequence targeting player score values.
     * @return A specialized {@link PlayerBuilder} for score manipulation.
     */
    public static PlayerBuilder players() {
        return new PlayerBuilder();
    }

    /**
     * Begins a batch operation to generate multiple commands at once, typically for initialization.
     * @return A new {@link BatchBuilder} instance.
     */
    public static BatchBuilder batch() {
        return new BatchBuilder();
    }

    // --- ⚙️ Core Contract ---

    /**
     * Returns the final command string generated by the specific builder branch.
     * @return The raw Minecraft command (e.g., "scoreboard players set...").
     */
    @Override
    public abstract String generate();

    /**
     * Standard override to allow the builder to be used directly in string concatenation.
     * <p><b>Safety:</b> Returns a comment block with error details if generation fails.</p>
     * @return The result of {@link #generate()}.
     */
    @Override
    public String toString() {
        try {
            return generate();
        } catch (Exception e) {
            return "/* Error generating command: " + e.getMessage() + " */";
        }
    }

    // --- 📦 Batch Management Branch ---

    /**
     * Handles bulk generation of scoreboard commands, primarily for registry initialization.
     */
    public static class BatchBuilder {

        /**
         * Generates a list of ScoreboardCommand builders for all registered objectives.
         * <p><b>Process:</b>
         * <ol>
         * <li>Iterates through {@code ScoreboardObjectives.ALL}.</li>
         * <li>Creates an 'add' command for every valid objective.</li>
         * <li>Creates a 'setdisplay' command if the objective is flagged for sidebar.</li>
         * </ol>
         * </p>
         * @return A non-null list of initialized ScoreboardCommand builders.
         * @throws RuntimeException if an error occurs during objective iteration.
         */
        public List<ScoreboardCommand> registerAll() {
            List<ScoreboardCommand> commandList = new ArrayList<>();

            try {
                for (uhc.score.ScoreboardObjective obj : uhc.score.ScoreboardObjectives.ALL) {
                    if (obj == null) continue;

                    // 1. Add the "Add Objective" builder
                    commandList.add(ScoreboardCommand.objectives().add(obj));

                    // 2. Add the "Set Display" builder if flagged for sidebar
                    if (obj.isDisplaySidebar()) {
                        commandList.add(ScoreboardCommand.objectives()
                                .setDisplay(uhc.score.DisplaySlot.SIDEBAR, obj.getId()));
                    }
                }
            } catch (Exception e) {
                throw new RuntimeException("CRITICAL: Failed to compile objective registration batch. Reason: " + e.getMessage(), e);
            }
            return commandList;
        }
    }

    // --- 🎯 Objective Management Branch ---

    /**
     * 🎯 **Objective Builder**
     * <p>Handles sub-commands under {@code /scoreboard objectives}, such as
     * adding, removing, or setting display slots for objectives.</p>
     */
    public static class ObjectiveBuilder extends ScoreboardCommand {

        /** The internal storage for the formatted sub-action string. */
        private String command;

        /**
         * Configures the command to register a new scoreboard objective.
         * @param obj The {@link ScoreboardObjective} data model.
         * @return This builder instance for chaining.
         * @throws NullPointerException if {@code obj} is null.
         * @throws IllegalStateException if the objective ID is invalid or missing.
         */
        public ObjectiveBuilder add(ScoreboardObjective obj) {
            Objects.requireNonNull(obj, "Objective data model cannot be null.");

            StringBuilder sb = new StringBuilder("add ")
                    .append(obj.getId().getObjectiveName())
                    .append(" ")
                    .append(obj.getCriteria().getCriteriaName());

            // Append optional JSON display name if present
            if (obj.getDisplayName() != null) {
                sb.append(" ").append(obj.getDisplayName().build());
            }

            this.command = sb.toString();
            return this;
        }

        /**
         * Configures the command to delete an existing objective from the registry.
         * @param id The unique {@link ScoreboardObjectiveId} to remove.
         * @return This builder instance for chaining.
         * @throws NullPointerException if the ID is null.
         */
        public ObjectiveBuilder remove(ScoreboardObjectiveId id) {
            Objects.requireNonNull(id, "Objective ID to remove cannot be null.");
            this.command = "remove " + id.getObjectiveName();
            return this;
        }

        /**
         * Sets where an objective should be displayed on the client UI.
         * @param slot The {@link DisplaySlot} destination (e.g., sidebar).
         * @param id   The objective ID to display, or null to clear the slot.
         * @return This builder instance for chaining.
         * @throws NullPointerException if the {@code slot} is null.
         */
        public ObjectiveBuilder setDisplay(DisplaySlot slot, ScoreboardObjectiveId id) {
            Objects.requireNonNull(slot, "Display slot cannot be null.");
            this.command = "setdisplay " + slot.getSlotName() + (id != null ? " " + id.getObjectiveName() : "");
            return this;
        }

        /**
         * Finalizes the {@code /scoreboard objectives} command string.
         * @return The formatted command.
         * @throws IllegalStateException if no builder action was called before generation.
         */
        @Override
        public String generate() {
            if (command == null) {
                throw new IllegalStateException("ObjectiveBuilder Error: No action (add, remove, setdisplay) was defined.");
            }
            return "scoreboard objectives " + command;
        }
    }

    // --- ⚔️ Player Management Branch ---

    /**
     * ⚔️ **Player Builder**
     * <p>Handles sub-commands under {@code /scoreboard players}, focusing on
     * modifying and querying scores for specific entities.</p>
     */
    public static class PlayerBuilder extends ScoreboardCommand {

        /** The entity selector or reference targeted by the command. */
        private Entity target;

        /** The partial command string representing the operation (set, get, add, reset). */
        private String subCommand;

        /**
         * Explicitly defines the entity whose scores will be processed.
         * @param target The {@link Entity} selector.
         * @return This builder instance for chaining.
         * @throws NullPointerException if the target is null.
         */
        public PlayerBuilder target(Entity target) {
            this.target = Objects.requireNonNull(target, "Player target entity cannot be null.");
            return this;
        }

        /**
         * Queries and returns the score of a player for a specific objective.
         * @param target    The {@link Entity} to query.
         * @param objective The {@link ScoreboardObjectiveId} to retrieve.
         * @return This builder instance.
         * @throws NullPointerException if either parameter is null.
         */
        public PlayerBuilder get(Entity target, ScoreboardObjectiveId objective) {
            Objects.requireNonNull(target, "Query Error: Target entity cannot be null.");
            Objects.requireNonNull(objective, "Query Error: Objective ID cannot be null.");

            this.target = target;
            this.subCommand = "get " + objective.getObjectiveName();
            return this;
        }

        /**
         * Sets the target's score to a specific numeric value.
         * @param id    The objective to modify.
         * @param score The value to set.
         * @return This builder instance.
         * @throws NullPointerException if objective ID is null.
         */
        public PlayerBuilder set(ScoreboardObjectiveId id, int score) {
            Objects.requireNonNull(id, "Objective ID for 'set' action cannot be null.");
            this.subCommand = "set " + id.getObjectiveName() + " " + score;
            return this;
        }

        /**
         * Adds a specific amount to the target's existing score.
         * @param id    The objective to modify.
         * @param score The amount to add.
         * @return This builder instance.
         * @throws NullPointerException if objective ID is null.
         */
        public PlayerBuilder add(ScoreboardObjectiveId id, int score) {
            Objects.requireNonNull(id, "Objective ID for 'add' action cannot be null.");
            this.subCommand = "add " + id.getObjectiveName() + " " + score;
            return this;
        }

        /**
         * Resets scores for the target.
         * @param id The specific objective to reset, or null to clear ALL scores for the player.
         * @return This builder instance.
         */
        public PlayerBuilder reset(ScoreboardObjectiveId id) {
            this.subCommand = "reset" + (id != null ? " " + id.getObjectiveName() : "");
            return this;
        }

        /**
         * Finalizes the {@code /scoreboard players} command string.
         * @return The formatted command.
         * @throws IllegalStateException if the target or the operation (subCommand) is missing.
         */
        @Override
        public String generate() {
            if (target == null) {
                throw new IllegalStateException("PlayerBuilder Error: No target entity provided. Use .target() or .get().");
            }
            if (subCommand == null) {
                throw new IllegalStateException("PlayerBuilder Error: No action (set, add, reset, get) was defined.");
            }

            try {
                // Injects the target between the action keyword and the objective/value
                return "scoreboard players " + subCommand.replaceFirst(" ", " " + target + " ");
            } catch (Exception e) {
                throw new IllegalStateException("CRITICAL: Failed to assemble player command structure: " + e.getMessage());
            }
        }
    }
}