package uhc;

import uhc.core.Datapack;
import uhc.core.Generator;
import uhc.core.Namespace;
import uhc.components.functions.Function;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class Main {

    /**
     * The target output directory for the final datapack folder.
     * The generator will create the 'my_uhc_datapack' folder inside this path.
     */
    private static final String OUTPUT_DIR_ROOT = "Server/world/datapacks";
    private static final String DATAPACK_NAME = "uhc_core_pack"; // The name of your custom namespace

    public static void main(String[] args) {

        // 1. **Define Datapack Metadata**
        Datapack datapack = new Datapack("A custom UHC Datapack generated by the UHC Datapack Creator.");

        // 2. **Get/Create the Custom Namespace**
        Namespace uhcNamespace = datapack.getOrCreateNamespace(DATAPACK_NAME);

        // 3. **Create and Populate Components (Functions)**

        // Create the 'load' function (runs once when the world loads)
        Function loadFunction = new Function("load");
        loadFunction.addCommand("say [UHC] Datapack initializing...");
        loadFunction.addCommand("scoreboard objectives add uhc_status dummy");
        uhcNamespace.addComponent(loadFunction);

        // Create the 'tick' function (runs every game tick)
        Function tickFunction = new Function("loop/tick");
        tickFunction.addCommand("# Run all loop operations here");
        tickFunction.addCommand("execute as @a run particle minecraft:cloud ~ ~ ~ 0.1 0.1 0.1 0 1 normal");
        uhcNamespace.addComponent(tickFunction);

        // 4. **Generate the Files**
        Generator generator = new Generator();

        // Use a Path object to handle OS-specific path separators correctly
        Path absolutePath = Paths.get(OUTPUT_DIR_ROOT).toAbsolutePath();

        System.out.println("Starting Datapack generation...");
        System.out.println("Target Directory: " + absolutePath);

        try {
            // The generate method handles creating all folders and writing content
            generator.generate(datapack, absolutePath.toString());
        } catch (IOException e) {
            System.err.println("FATAL ERROR: Could not generate datapack.");
            e.printStackTrace();
        }
    }
}