function preAssignedTeams = importTeams(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PREASSIGNEDTEAMS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  PREASSIGNEDTEAMS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  preAssignedTeams = importfile("C:\Users\bthem\Documents\UHC-Datapack-Creator\Files\DIORITE\preAssignedTeams.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Mar-2024 12:18:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName3", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName3", "ThousandsSeparator", ",");

% Import the data
preAssignedTeams = readtable(filename, opts);

%% Convert to output type
preAssignedTeams = table2array(preAssignedTeams);
end